### ISSUE TITLE
assoc-in bug

### ISSUE THREAD

**Issue by pkpkpk** [replikativ/konserve#120]
[this](https://github.com/replikativ/konserve/blob/1875076715418bac78b9e70cdb31631282e85615/src/konserve/impl/defaults.cljc#L363) should update nested paths instead of overwriting root value.

Expected behavior should be more akin to:

```clj
(defn assoc-in
  [store key-vec val opts]
  (let [[path-vec key] ((juxt pop peek) key-vec)]
    (k/update-in store path-vec #(clojure.core/assoc % key val) opts)))
```

Simple fix but given its duration should be grouped into a breaking-change release

**Comment by nalcabio-tom** [comment]
Thanks for reporting this. Been really scratching my head because of this

**Comment by nalcabio-tom** [comment]
This is what worked for me:

```clojure
(defn- -assoc-in
  [db path v opts]
  (let [[k p] ((juxt first rest) path)]
    (k/update db k #(if (seq p) (assoc-in % p v) v) opts)))
```
