### ISSUE TITLE
db corruption

### ISSUE THREAD

**Issue by grischoun** [replikativ/konserve#16]
Using Konserve with indexeddb, instead of correctly computing a value I received an error and mistakenly saving the error instead of the value led to database corruption.

**Comment by whilo** [comment]
Can you give more details on the error, e.g. the string that is saved in the DB?

**Comment by grischoun** [comment]
Impossible to copy/string from Firefox db inspector but here is a screenshot illustrating the error:

![screen shot 2018-04-07 at 11 57 02](https://user-images.githubusercontent.com/11461/38453762-2f127830-3a5b-11e8-8d1f-3412755cbd18.png)

Here is what I expect when it is working well:

![screen shot 2018-04-07 at 12 01 03](https://user-images.githubusercontent.com/11461/38453783-755b7d5a-3a5b-11e8-9acf-18f1f04ce61f.png)

Is this enough for you?

**Comment by whilo** [comment]
Yes, perfect. In the first thing you have somehow written code to the store, but not konserve code, but some application JS. I don't think it is a konserve bug, but maybe you see a bug. I am not sure whether we can cover that, except with specing (which is a good idea).

**Comment by whilo** [comment]
I will close this for now. Feel free to reopen, if the issue pops up again.
