### ISSUE TITLE
nested assoc and get behaviour expectations

### ISSUE THREAD

**Issue by shakdwipeea** [replikativ/konserve#17]
I tried the following actions:
```
(def store (<!! (new-fs-store "./database")))

(<!! (k/assoc-in store [:foo :bar] 20))
(<!! (k/assoc-in store [:foo :baz] 40))
(<!! (k/assoc-in store [:foo :ant] 40))

(<!! (k/get-in store [:foo :baz])) ;; => {:bar 20, :baz 40, :ant 40}

(<!! (k/get-in store [:foo])) ;; => {:bar 20, :baz 40, :ant 40}
```
I was expecting `(<!! (k/get-in store [:foo :baz]))` to return 40 instead of the entire map.

**Comment by whilo** [comment]
This was slipping through when I added cache support for beta1. beta2 has fixed it now and there is a test covering it, thanks for reporting!

**Comment by shakdwipeea** [comment]
Works as expected now. Thanks for looking into this.
