### ISSUE TITLE
The API should have more clojure.core-like signatures

### ISSUE THREAD

**Issue by MrEbbinghaus** [replikativ/konserve#24]
I have a list of proposals to move the API closer to the clojure.core interface. 

- [ ] There is no `get`, `assoc` and `update` function. 
  - These should be trivial without touching any interface. 
- [ ] The `update-in` function does not have the optional arguments for the function.
   - clojure.core: `(update-in m ks f & args)`
- [ ] `get-in` does not have an optional argument for a default value.

None of these proposals will break the current API.

**Comment by whilo** [comment]
I am fine to extend the core namespace to provide these functions in `core.clj`. It would also make sense to provide ! (bang) versions for Clojure so that people do not need to work with core.async if they do not like to. Could you create a PR for that?
