### ISSUE TITLE
Persistent durable datastructures

### ISSUE THREAD

**Issue by whilo** [replikativ/konserve#4]
There is a desire to go beyond the append-log in konserve and provide an efficient index for different use cases. There is a quick prototype https://github.com/replikativ/durable-persistence, but in general https://github.com/datacrypt-project/hitchhiker-tree seems optimal from its IO ops performance. This issue is to track different requirements and thoughts for an implementation until it is provided.

**Comment by danielsz** [comment]
I suppose a low-hanging fruit is to implement a high-level protocol that would directly map the Outboard API (`ob/insert`, `ob/lookup`) with  Konserve's user API (`k/assoc-in`, `k/get-in`), but I'm not sure that's a good idea.

**Comment by whilo** [comment]
First of all the files in Tree are pure and there is a pure in-memory `TestingBackend`, so the redis stuff can be separated. Having a look at redis.clj there are also some functions which use lua in redis directly, but they don't seem to be used. So at least the functions from the tree folder with all the balancing logic should be portable. The problem without outboard is that it is modelling an interpreter for redis commands and I haven't wrapped my head around it yet. I think just replacing the messaging (which steers the interpreter) with direct IO won't work.

**Comment by whilo** [comment]
Just to ping back here: The hitchhiker-tree has now konserve support in upstream: https://github.com/datacrypt-project/hitchhiker-tree We will continue to build on it. If you have any further remarks, feel free to reopen the issue.

**Comment by danielsz** [comment]
Oh, I missed your commit upstream. I was watching that repo and must have despaired because it was so quiet for so long. That's really good news. I'll take a closer look when I have some time. Thank you!

**Comment by whilo** [comment]
No problem. :)
