### ISSUE TITLE
CLJS builds don't work

### ISSUE THREAD

**Issue by RokLenarcic** [replikativ/konserve#70]
When compiling CLJS with konserve version 0.6.0-alpha3, you'll get this error:
```
[:main] Compiling ...
[:main] Build failure:
The required namespace "incognito.fressian" is not available, it was required by "konserve/serializers.cljc".
"incognito/fressian.clj" was found on the classpath. Maybe this library only supports CLJ?
```

Seems like project is using fressian and it's not available in CLJS

**Comment by whilo** [comment]
I think cljs support should be recovered now thanks to @pkpkpk. If not please reopen the issue.
