### ISSUE TITLE
encryptor-ns for cljs

### ISSUE THREAD

**Issue by TimoKramer** [replikativ/konserve#96]
@whilo cljs support is now broken since encryptor-ns uses java.io.

**Comment by jsmassa** [comment]
PR #90 includes a temporary fix now, with usage of a salt still missing though.

**Comment by whilo** [comment]
I had cljs support also working initially without salt, but I need to take a look again how the buffer concatenation works in cljs. Without salt the encryption is kind of broken (see link). I will try to fix it on the weekend.

**Comment by whilo** [comment]
This is fixed now with #90.
